# Generated by Django 3.2.6 on 2021-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('food', models.CharField(max_length=250, verbose_name='Кухня')),
                ('full_text', models.TextField(verbose_name='Информация о ресторане')),
                ('date', models.DateTimeField(verbose_name='Дата открытия')),
                ('tel', models.CharField(max_length=250, verbose_name='Tелефон')),
                ('url', models.CharField(max_length=250, verbose_name='URL ресторана')),
                ('addr', models.CharField(max_length=250, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
    ]
